spring:
  application:
    name: Blogex
  profiles:
    active: default
  datasource:
    url: "jdbc:mysql://localhost:3306/nexioblog?serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    username: "nexio_use"
    password: "nexio_user@2019"

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
    show-sql: true

  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
#    url: "jdbc:mysql://localhost:3306/nexioblog?serverTimezone=UTC"
#    user: "optimizuser"
#    password: "mysql@optimiz123"

server:  port: 8090

